# Generated by Django 5.0.4 on 2024-04-11 01:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='date_Achat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
