# Generated by Django 5.0.6 on 2024-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
